### ISSUE TITLE
icon picker doesn't pickup the relative instance for dynamic DOM elements

### ISSUE THREAD

**Issue by saptarang** [itsjaviaguilar/fontawesome-iconpicker#24]
![icon-picker](https://cloud.githubusercontent.com/assets/8026272/18667574/ca1ba294-7f4e-11e6-8e2f-62cf301c8cb7.png)
![iconpicker-issue](https://cloud.githubusercontent.com/assets/8026272/18667575/ca73267c-7f4e-11e6-82ac-baca00aacaf4.png)

I'm working with **ReduxFramework** for WordPress and i'm using the **Slides** field for creating a slideshow. So if I have two slides added, the icon picker **creates and popup relative instance of picker** for the associated INPUT field. so far so good. When add a NEW SLIDE which is a dynamic jQuery object in DOM, the icon picker doesn't pickup its own instance of picker BUT picks up the one from already existing slide item. When i inspected the html structure for the NEW DYNAMIC ELEMENT, I can see the instance of picker appended next to it but it does not show it when the INPUT is FOCUSED or clicked.

Let me know if I'm making any sense in this :)

**Code Reference:**
This code is added in a javascript file which is added in the WordPress Admin using action filter.

`// Icon Picker
	function openIcoPicker(elm) {
		$(elm).iconpicker({
		    placement: 'topLeft',
		    hideOnSelect: true
		});
	}
	// assign additonal required classes to new elements
	$('.redux-slides-list').each(function() {
	  	$(this).find('li:eq(2) input').addClass('icp icp-auto').iconpicker();
	});
	$('.icp').on("click", function() {
		openIcoPicker(this);				
	}).trigger('click');`

Regards
Saptarang

**Comment by itsjaviaguilar** [comment]
`$('.icp').on("click", function() { openIcoPicker(this); }).trigger('click');`

You are basically trying to open all of them at the same time.
